fix: error TS6137: Cannot import type declaration files. Consider importing 'express' instead of '@types/express'
for more info see https://github.com/Microsoft/TypeScript/issues/16472